### ISSUE TITLE
Feature - limited set of sprite colors

### ISSUE THREAD

**Issue by jdimauro** [jdimauro/witch-lights#11]
I want sprites to choose randomly from an array of pre-set colors. 
- Purple
- Green
- Blue
- Yellow

These will be hex codes which I will tune to get their color right. 

It'd be especially cool if each color corresponded to a specific type of sprite animation.

**Comment by tenner** [comment]
This was added in the 2017 edition.

Set these two parameters:
```
#define NUM_COLORSETS         5
#define NUM_COLORS_PER_SET    9
```

And define as many colorsets as you like (so long as you still have memory) in the `createColorsets()` method. Because the number of colorsets and the array dimensions are created from the preprocessor directive, be sure to `#if`/`#endif` the declarations too to make sure nobody writes out of bounds.

```
// Yellow-green.
#if NUM_COLORSETS > 1
    colorSets[1][0] = 0x000000;
    colorSets[1][1] = 0x000000;
    colorSets[1][2] = 0x000100;
    colorSets[1][3] = 0x010200;
    colorSets[1][4] = 0x030500;
    colorSets[1][5] = 0x060A01;
    colorSets[1][6] = 0x0D1503;
    colorSets[1][7] = 0x1B2A06;
    colorSets[1][8] = 0x36540C;
#endif
```

The number of colors in each set is also theoretically infinite, however the color choice for each pixel in an animation is handled by choosing the color assigned to each character in an animation string. For now these are blank for 0, and characters '1'-'9' for 1-9; for more colors you can continue up the ASCII chart or re-develop that function to support more than 9 characters.
